import enum

from pydantic import BaseModel, Field


class SecurityType(enum.StrEnum):
    STOCK = "STOCK"
    INDEX = "INDEX"
    BOND = "BOND"


class OrderSide(enum.StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class TimeInForce(enum.StrEnum):
    DAY = "DAY"
    GTC = "GTC"
    IOC = "IOC"
    OPG = "OPG"


class OrderPlacementStatus(enum.StrEnum):
    SUBMITTED = "SUBMITTED"
    NEEDS_CONFIRMATION = "NEEDS_CONFIRMATION"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"


class OrderPlacementResult(BaseModel):
    status: OrderPlacementStatus = Field(
        description=(
            "Outcome of the request. SUBMITTED means the order was accepted by "
            "Interactive Brokers. NEEDS_CONFIRMATION means the order is NOT live yet: "
            "Interactive Brokers returned the warnings in 'messages' and the order is "
            "only sent to the market after calling confirmOrder with 'reply_id'. "
            "REJECTED means the order was refused, see 'error'. UNKNOWN means the "
            "outcome could not be determined and must be reconciled with getLiveOrders."
        )
    )
    client_order_id: str | None = Field(
        default=None,
        description=(
            "Client order ID generated by this server when the order was placed. If "
            "the outcome is unclear, call getLiveOrders and match this value against "
            "the client_order_id of each entry. Not set on confirmOrder results."
        ),
    )
    order_id: str | None = Field(
        default=None,
        description="Interactive Brokers order ID, present once the order is accepted.",
    )
    order_status: str | None = Field(
        default=None,
        description="Status of the order as reported by Interactive Brokers.",
    )
    reply_id: str | None = Field(
        default=None,
        description=(
            "ID of the warning that must be answered with confirmOrder before the "
            "order is sent to the market. Null when Interactive Brokers accepted or "
            "rejected the order outright."
        ),
    )
    messages: list[str] | None = Field(
        default=None,
        description=(
            "Warnings raised by Interactive Brokers that must be reviewed before "
            "confirming the order."
        ),
    )
    error: str | None = Field(
        default=None,
        description="Reason the order was rejected by Interactive Brokers.",
    )


class OrderStatus(BaseModel):
    order_id: int | None = Field(
        default=None, description="Interactive Brokers order ID."
    )
    status: str | None = Field(
        default=None,
        description=(
            "Status as reported by Interactive Brokers, e.g. PendingSubmit, "
            "PreSubmitted, Submitted, Filled, Cancelled, Inactive. An order only "
            "reached the market once it is Submitted or beyond."
        ),
    )
    status_description: str | None = Field(
        default=None, description="Human readable explanation of the status."
    )
    side: OrderSide | None = Field(
        default=None, description="Whether the order buys or sells."
    )
    symbol: str | None = Field(default=None, description="Symbol being traded.")
    company_name: str | None = Field(
        default=None, description="Name of the company behind the symbol."
    )
    contract_id: int | None = Field(
        default=None, description="Contract ID of the security being traded."
    )
    sec_type: str | None = Field(
        default=None, description="Security type of the contract."
    )
    listing_exchange: str | None = Field(
        default=None, description="Exchange the contract is listed on."
    )
    currency: str | None = Field(
        default=None, description="Currency the order is denominated in."
    )
    order_type: str | None = Field(
        default=None, description="Order type, e.g. MARKET or LIMIT."
    )
    total_quantity: float | None = Field(
        default=None, description="Total size of the order."
    )
    filled_quantity: float | None = Field(
        default=None, description="Quantity filled so far."
    )
    remaining_quantity: float | None = Field(
        default=None,
        description=(
            "Quantity still outstanding, derived by this server as total minus "
            "filled. Null when either figure is missing."
        ),
    )
    average_price: float | None = Field(
        default=None,
        description="Average price of the fills so far. Null while the order is unfilled.",
    )
    limit_price: float | None = Field(
        default=None, description="Limit price, if the order has one."
    )
    stop_price: float | None = Field(
        default=None, description="Stop price, if the order has one."
    )
    time_in_force: str | None = Field(
        default=None, description="How long the order stays active."
    )
    outside_regular_trading_hours: bool | None = Field(
        default=None,
        description="Whether the order is eligible to execute outside regular hours.",
    )
    order_time: str | None = Field(
        default=None,
        description="Time the order was submitted, as reported by Interactive Brokers.",
    )
    description: str | None = Field(
        default=None, description="Interactive Brokers' description of the order."
    )
    cannot_cancel: bool | None = Field(
        default=None, description="Whether the order can no longer be cancelled."
    )


class LiveOrder(BaseModel):
    order_id: int | None = Field(
        default=None, description="Interactive Brokers order ID."
    )
    client_order_id: str | None = Field(
        default=None,
        description=(
            "Client order ID this server generated when placing the order, as filed by "
            "Interactive Brokers. Use it to match an order back to a placeOrder call "
            "whose outcome was unclear."
        ),
    )
    account_id: str | None = Field(
        default=None, description="Account the order belongs to."
    )
    status: str | None = Field(
        default=None,
        description=(
            "Status as reported by Interactive Brokers, e.g. PendingSubmit, "
            "PreSubmitted, Submitted, Filled, Cancelled, Inactive."
        ),
    )
    side: OrderSide | None = Field(
        default=None, description="Whether the order buys or sells."
    )
    ticker: str | None = Field(default=None, description="Symbol being traded.")
    company_name: str | None = Field(
        default=None, description="Name of the company behind the symbol."
    )
    contract_id: int | None = Field(
        default=None, description="Contract ID of the security being traded."
    )
    sec_type: str | None = Field(
        default=None, description="Security type of the contract."
    )
    listing_exchange: str | None = Field(
        default=None, description="Exchange the contract is listed on."
    )
    currency: str | None = Field(
        default=None, description="Currency the order is denominated in."
    )
    order_type: str | None = Field(
        default=None, description="Order type, e.g. Market or Limit."
    )
    total_quantity: float | None = Field(
        default=None, description="Total size of the order."
    )
    filled_quantity: float | None = Field(
        default=None, description="Quantity filled so far."
    )
    remaining_quantity: float | None = Field(
        default=None, description="Quantity still outstanding, as reported by IB."
    )
    average_price: float | None = Field(
        default=None,
        description="Average price of the fills so far. Null while the order is unfilled.",
    )
    limit_price: float | None = Field(
        default=None, description="Limit price, if the order has one."
    )
    stop_price: float | None = Field(
        default=None, description="Stop price, if the order has one."
    )
    time_in_force: str | None = Field(
        default=None, description="How long the order stays active."
    )
    last_execution_time: str | None = Field(
        default=None, description="Time of the most recent execution."
    )
    description: str | None = Field(
        default=None, description="Interactive Brokers' description of the order."
    )


class Trade(BaseModel):
    execution_id: str | None = Field(
        default=None,
        description="Interactive Brokers execution ID, unique per fill.",
    )
    client_order_id: str | None = Field(
        default=None,
        description=(
            "Client order ID this server generated when placing the order, as filed by "
            "Interactive Brokers. Use it to tie an execution back to a placeOrder call."
        ),
    )
    account_id: str | None = Field(
        default=None, description="Account the trade was executed in."
    )
    trade_time: str | None = Field(
        default=None,
        description="Execution time as reported by Interactive Brokers, in UTC.",
    )
    side: OrderSide | None = Field(
        default=None, description="Whether the trade bought or sold."
    )
    symbol: str | None = Field(default=None, description="Symbol traded.")
    company_name: str | None = Field(
        default=None, description="Name of the company behind the symbol."
    )
    contract_id: int | None = Field(
        default=None, description="Contract ID of the security traded."
    )
    sec_type: str | None = Field(
        default=None, description="Security type of the contract."
    )
    quantity: float | None = Field(
        default=None, description="Quantity filled by this execution."
    )
    price: float | None = Field(
        default=None, description="Price this execution filled at."
    )
    net_amount: float | None = Field(
        default=None, description="Net cash value of the execution."
    )
    commission: float | None = Field(
        default=None, description="Commission charged on this execution."
    )
    exchange: str | None = Field(
        default=None, description="Exchange the execution took place on."
    )
    order_type: str | None = Field(
        default=None, description="Type of the order that produced this execution."
    )
    description: str | None = Field(
        default=None, description="Interactive Brokers' description of the trade."
    )


class Transaction(BaseModel):
    date: str | None = Field(
        default=None,
        description="Date of the transaction as reported by Interactive Brokers.",
    )
    type: str | None = Field(
        default=None,
        description=(
            "Kind of transaction, e.g. Buy, Sell, Dividend or a transfer. Unlike "
            "getTrades, this is not limited to executions."
        ),
    )
    description: str | None = Field(
        default=None, description="Description of the instrument or the cash movement."
    )
    contract_id: int | None = Field(
        default=None, description="Contract ID the transaction relates to."
    )
    quantity: float | None = Field(
        default=None,
        description=(
            "Quantity transacted. Negative for sells and positive for buys, so this "
            "is signed rather than absolute."
        ),
    )
    price: float | None = Field(
        default=None, description="Price per unit for the transaction."
    )
    amount: float | None = Field(
        default=None, description="Cash amount of the transaction."
    )
    currency: str | None = Field(
        default=None, description="Currency the amount is reported in."
    )
    fx_rate_to_base: float | None = Field(
        default=None,
        description="Rate used to convert the amount into the account's base currency.",
    )
    account_id: str | None = Field(
        default=None, description="Account the transaction belongs to."
    )


class Account(BaseModel):
    id: str = Field(description="The account ID.")
    account_van: str | None = Field(default=None, description="The account alias.")
    account_title: str | None = Field(default=None, description="Title of the account.")
    display_name: str | None = Field(
        default=None, description="Display name of the account."
    )
    account_alias: str | None = Field(
        default=None, description="User customizable account alias."
    )
    account_status: int | None = Field(
        default=None, description="Unix timestamp of when the account was opened."
    )
    currency: str | None = Field(
        default=None, description="Base currency of the account."
    )
    type: str | None = Field(
        default=None, description="Account type (e.g. INDIVIDUAL, IRA, DEMO)."
    )
    trading_type: str | None = Field(
        default=None, description="Account trading structure (e.g. PMRGN, STKCASH)."
    )
    business_type: str | None = Field(
        default=None, description="Organizational structure of the account."
    )
    ib_entity: str | None = Field(
        default=None, description="Interactive Brokers entity the account is tied to."
    )
    fa_client: bool | None = Field(
        default=None,
        description="Whether the account is a sub-account of a Financial Advisor.",
    )
    clearing_status: str | None = Field(
        default=None,
        description="Status of the account. O=Open, P/N=Pending, A=Abandoned, R=Rejected, C=Closed.",
    )
    covestor: bool | None = Field(
        default=None, description="Whether this is a Covestor account."
    )
    no_client_trading: bool | None = Field(
        default=None,
        description="Whether the client account is restricted from trading.",
    )
    track_virtual_fx_portfolio: bool | None = Field(
        default=None, description="Whether the account tracks a Virtual FX portfolio."
    )
    desc: str | None = Field(
        default=None,
        description="Account description in the format 'accountId - accountAlias'.",
    )


class AccountSummary(BaseModel):
    currency: str | None = Field(
        default=None,
        description="Base currency of the account. Every amount below is reported in it.",
    )
    net_liquidation: float | None = Field(
        default=None,
        description="Total value of the account if every position were liquidated.",
    )
    total_cash_value: float | None = Field(
        default=None, description="Total cash held in the account."
    )
    settled_cash: float | None = Field(
        default=None,
        description="Cash that has settled and is available without a margin loan.",
    )
    accrued_cash: float | None = Field(
        default=None,
        description="Interest and dividends accrued but not yet posted as cash.",
    )
    buying_power: float | None = Field(
        default=None,
        description=(
            "Maximum notional value of securities that can be bought right now, "
            "including margin leverage. Larger than the available cash on a margin "
            "account."
        ),
    )
    available_funds: float | None = Field(
        default=None,
        description="Funds available for trading or withdrawal after margin requirements.",
    )
    excess_liquidity: float | None = Field(
        default=None,
        description=(
            "Buffer above the maintenance margin requirement. A value at or below "
            "zero means the account is at risk of forced liquidation."
        ),
    )
    equity_with_loan_value: float | None = Field(
        default=None,
        description="Account value Interactive Brokers will lend against.",
    )
    gross_position_value: float | None = Field(
        default=None,
        description="Total absolute market value of all open positions.",
    )
    initial_margin_requirement: float | None = Field(
        default=None, description="Margin required to open the current positions."
    )
    maintenance_margin_requirement: float | None = Field(
        default=None, description="Margin required to keep the current positions open."
    )
    cushion: float | None = Field(
        default=None,
        description=(
            "Margin cushion as a fraction, not a percentage: excess liquidity divided "
            "by net liquidation value. Closer to zero means closer to liquidation."
        ),
    )
    unrealized_pnl: float | None = Field(
        default=None, description="Profit or loss on open positions."
    )
    realized_pnl: float | None = Field(
        default=None, description="Profit or loss realized through closed trades."
    )
    day_trades_remaining: float | None = Field(
        default=None,
        description=(
            "Day trades still allowed over the rolling five day window. -1 means "
            "unlimited."
        ),
    )
    account_type: str | None = Field(
        default=None, description="Account type as reported by Interactive Brokers."
    )


class CurrencyBalance(BaseModel):
    currency: str = Field(
        description=(
            "Currency of this balance. 'BASE' is the account-wide total converted into "
            "the account's base currency; the other entries are the individual "
            "currencies held, so summing across entries double counts."
        )
    )
    cash_balance: float | None = Field(
        default=None, description="Cash held in this currency."
    )
    settled_cash: float | None = Field(
        default=None, description="Settled cash held in this currency."
    )
    net_liquidation_value: float | None = Field(
        default=None, description="Net liquidation value attributed to this currency."
    )
    stock_market_value: float | None = Field(
        default=None, description="Market value of stock positions in this currency."
    )
    exchange_rate: float | None = Field(
        default=None,
        description="Rate used to convert this currency into the account's base currency.",
    )
    unrealized_pnl: float | None = Field(
        default=None, description="Unrealized profit or loss in this currency."
    )
    realized_pnl: float | None = Field(
        default=None, description="Realized profit or loss in this currency."
    )
    interest: float | None = Field(
        default=None, description="Accrued interest in this currency."
    )
    dividends: float | None = Field(
        default=None, description="Accrued dividends in this currency."
    )


class SecuritySearchResult(BaseModel):
    contract_id: str
    company_header: str
    company_name: str | None = None
    symbol: str | None = None
    description: str | None = None
    restricted: str | None = None
    bondid: int | None = None


class Position(BaseModel):
    position: float | None = Field(
        default=None, description="The total size of the position."
    )
    contract_id: str | None = Field(
        default=None, description="The contract ID of the position."
    )
    avg_cost: float | None = Field(
        default=None,
        description="The average cost of each share in the position times the multiplier.",
    )
    avg_price: float | None = Field(
        default=None,
        description="The average cost of each share in the position when purchased.",
    )
    currency: str | None = Field(
        default=None, description="The traded currency for the contract."
    )
    symbol: str | None = Field(
        default=None, description="The local symbol of the position."
    )
    market_price: float | None = Field(
        default=None, description="The current market price of each share."
    )
    market_value: float | None = Field(
        default=None, description="The total market value of the position."
    )
    realized_pnl: float | None = Field(
        default=None, description="The total profit realized today through trades."
    )
    unrealized_pnl: float | None = Field(
        default=None,
        description="The total potential profit if the position were closed.",
    )
    sec_type: str | None = Field(
        default=None, description="The asset class or security type of the contract."
    )
    asset_class: str | None = Field(
        default=None, description="The asset class or security type of the contract."
    )
    timestamp: int | None = Field(
        default=None, description="The epoch timestamp of the portfolio request."
    )


class SecurityInformation(BaseModel):
    contract_id: int
    symbol: str
    currency: str
    company_name: str | None = None
    instrument_type: str | None = None
    exchange: str | None = None
    valid_exchanges: str | None = None
    trading_class: str | None = None
    industry: str | None = None
    category: str | None = None
    local_symbol: str | None = None
    cfi_code: str | None = None
    cusip: str | None = None
    expiry_full: str | None = None
    maturity_date: str | None = None
